plugin: amazon.aws.aws_ec2  # ✅ correct plugin name
regions:
  - ap-south-1
filters:
  tag:Name:
    
    - KafkaPrivate1
    - KafkaPrivate2
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: ""
hostnames:
  - private-ip-address
strict: False
