---
# vars file for kafka_role

kafka_download_url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
kafka_archive: "kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
kafka_dir: "kafka_{{ scala_version }}-{{ kafka_version }}"
