---

- name: update cache
  apt: 
   update_cache: yes

- name: install python
  command: apt install python3 -y

- name: Download java
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Download Kafka
  get_url:
      url: "{{ kafka_download_url }}"
      dest: /home/ubuntu/{{ kafka_archive }}
      mode: '0644'
  become: yes

- name: extract kafka
  unarchive:
       src: /home/ubuntu/{{ kafka_archive }}
       dest: /home/ubuntu/
       remote_src: yes
  become: yes

- name: set ownership to user
  file:
    path: /home/ubuntu/{{ kafka_dir }}
    owner: ubuntu
    group: ubuntu
  become: yes

- name: remove old kafka dir
  file: 
    path: /home/ubuntu/kafka
    state: absent




- name: rename the kafka directory
  shell: mv -f /home/ubuntu/{{ kafka_dir }} /home/ubuntu/kafka
  become: yes
   
- name: generate uuid
  shell: "/home/ubuntu/kafka/bin/kafka-storage.sh random-uuid"
  register: kafka_uuid

- name: Remove old kafka storage logs
  file:
    path: /tmp/kraft-combined-logs
    state: absent



- name: format kraft log directory 
  shell: "/home/ubuntu/kafka/bin/kafka-storage.sh format -t {{ kafka_uuid.stdout }} -c /home/ubuntu/kafka/config/kraft/server.properties && touch /tmp/kafka-formatted"
  args: 
    creates: /tmp/kafka-formatted
  become: yes

- name: Set ownership for /tmp/kraft-combined-logs
  file:
    path: /tmp/kraft-combined-logs
    owner: ubuntu
    group: ubuntu
    recurse: yes
  become: yes
  
- name: Create systemd unit file for Kafka
  copy:
    dest: /etc/systemd/system/kafka.service
    content: |
      [Unit]
      Description=Apache Kafka Server
      After=network.target

      [Service]
      Type=simple
      User=ubuntu
      ExecStart=/home/ubuntu/kafka/bin/kafka-server-start.sh /home/ubuntu/kafka/config/kraft/server.properties
      Restart=on-abnormal

      [Install]
      WantedBy=multi-user.target
  become: yes

- name: Reload systemd daemon
  shell: systemctl daemon-reexec
  become: yes

- name: Enable Kafka service
  systemd:
    name: kafka
    enabled: yes
  become: yes

- name: Start Kafka service
  systemd:
    name: kafka
    state: started
  become: yes
