- name: Install Ansible on Ubuntu and run kafka
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: install pyhton
      command: apt install python3 -y 


    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Copy role directory
      synchronize:
        src: /home/ishaan/Devops/KAFKA/ansible/kafka_install/
        dest: /home/ubuntu/kafka_install/
        recursive: yes

    - name: directory permsiion
      file: 
        path: /home/ubuntu/kafka_install
        owner: ubuntu
        group: ubuntu
        recurse: yes
        mode: '0755'   
      become: yes

    - name: copy key
      copy:
       src: /home/ishaan/UNIX/slave.pem
       dest: /home/ubuntu
       mode: '0400'
       owner: ubuntu
       group: ubuntu
      become: yes

